name: 'Build & Test'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  javascript_unit_tests:
    name: Unit tests - javascript
    runs-on: macos-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Node
        uses: actions/setup-node@v1

      - name: Install npm dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Run unit tests
        run: |
          yarn test

  java_unit_tests:
    name: Unit tests - java
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install npm dependencies
        working-directory: ./examples/detox
        run: |
          yarn install --frozen-lockfile

      - name: Run unit tests
        working-directory: ./examples/detox/android
        run: ./gradlew testDebugUnitTest
