name: Build Android

on:
  workflow_call:
  workflow_dispatch:

jobs:
  e2e-maestro:
    runs-on: ubuntu-latest
    outputs:
      app: app/build/outputs/apk/release
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: cache
        with:
          path: examples/Rn069/android/app/build/outputs/apk/release/app-release.apk
          key: ${{ runner.os }}-${{ hashFiles('src/**', 'android/**', env.EXAMPLE_SRC ) }}

      - uses: actions/setup-node@v3
        with:
          node-version: 14.18.1
          cache: 'yarn'

      - name: Install npm dependencies (example project)
        working-directory: ./examples/Rn069/
        run: yarn install --frozen-lockfile

      - name: Install npm dependencies (root)
        working-directory: ./
        run: yarn install --frozen-lockfile

      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: build
        working-directory: ./examples/Rn069/android
        run: ./gradlew assembleRelease
