name: E2E tests (ios)

on:
  workflow_dispatch:
  push:

jobs:
  e2e-maestro-ios:
    name: Build
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14.18.1
          cache: 'yarn'

      - name: Install npm dependencies (example project)
        working-directory: ./examples/Rn071/
        run: yarn install --frozen-lockfile

      - name: Install npm dependencies (root)
        working-directory: ./
        run: yarn install --frozen-lockfile

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: ./examples/Rn071/

      - name: setup-cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: 1.11.3

      - name: Install CocoaPods
        working-directory: ./examples/Rn071/
        run: |
          yarn pods

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_$(<.xcode-version).app/Contents/Developer

      - name: Build
        working-directory: ./examples/Rn071/ios/
        run: |
          set -o pipefail && xcodebuild \
            -workspace "Rn071.xcworkspace" \
            -scheme "Rn071" \
            -destination "platform=iOS Simulator,name=iPhone 14,OS=16.4" \
            -derivedDataPath "DerivedData" \
          | tee xcodebuild.log

      - name: ls
        working-directory: ./examples/Rn071/ios/
        run: |
          ls -la DerivedData
          ls -la DerivedData/Build/Products
          ls -la ./examples/Rn071
          ls -la ./examples/Rn071/ios

      - uses: mobile-dev-inc/action-maestro-cloud@v1.4.0
        # Temp
        if: always()
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: ./examples/Rn071/DerivedData/Build/Products/Debug-iphonesimulator/Rn071.app

      - name: Upload logs when workflow failed
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: BuildLogs
          path: |
            xcodebuild.log
            DerivedData/Logs/Test/*.xcresult
