name: E2E tests (ios)

# Android + iOS maestro tests by environment
# PR flow that includes all testing + build in a different step from maestro

on:
  workflow_dispatch:
  pull_request:
  push: # temp

env:
  APP_PATH: ./examples/Rn071/ios/DerivedData/Build/Products/Release-iphonesimulator/Rn071.app
  PROJECT_NAME: Rn071
  EXAMPLE_SRC: ./examples/Rn071/src/**

jobs:
  build-ios:
    name: Build iOS
    uses: ./.github/workflows/build-ios.yml
    secrets: inherit

  e2e-ios:
    name: e2e tests
    runs-on: macos-13
    environment: e2e
    needs: [build-ios]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ${{ env.APP_PATH }}
            ${{ env.APP_PATH }}.dSYM
          key: ${{ runner.os }}-${{ hashFiles('src/**', 'ios/**', env.EXAMPLE_SRC ) }}

      - uses: mobile-dev-inc/action-maestro-cloud@v1.8.0
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: ${{ env.APP_PATH }}
          mapping-file: ${{ env.APP_PATH }}.dSYM
          include-tags: ios

      - name: Upload logs when workflow failed
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: BuildLogs
          path: |
            xcodebuild.log
            DerivedData/Logs/Test/*.xcresult
