name: E2E tests (maestro local)

on:
  workflow_dispatch:
  push:

jobs:
  e2e-maestro:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14.18.1
          cache: 'yarn'

      - name: Install npm dependencies (example project)
        working-directory: ./examples/Rn069/
        run: yarn install --frozen-lockfile

      - name: Install npm dependencies (root)
        working-directory: ./
        run: yarn install --frozen-lockfile

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck

      - name: build
        working-directory: ./examples/Rn069/android
        run: ./gradlew assembleRelease

      - name: Install maestro
        run: curl -Ls "https://get.maestro.mobile.dev" | bash

      - uses: mobile-dev-inc/action-maestro-cloud@v1.1.1
        run: maestro test .maestro/timezone-offset-in-minutes.yml
