name: Build and upload to Maestro Cloud

on:
  push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  maestro-cloud:
    runs-on: ubuntu-latest
    outputs:
      app: app/build/outputs/apk/release
    steps:
      - uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v2

      - name: Install npm dependencies
        working-directory: ./examples/Rn069
        run: yarn install --frozen-lockfile --network-timeout 60000

      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: build
        working-directory: ./examples/Rn069/android
        run: ./gradlew assembleRelease

      - uses: mobile-dev-inc/action-maestro-cloud@v1.1.1
        working-directory: ./examples/Rn069/android
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: app/build/outputs/apk/release/app-release.apk
