name: Build and upload to Maestro Cloud

on:
  push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  maestro-cloud:
    runs-on: ubuntu-latest
    outputs:
      app: app/build/outputs/apk/release
    steps:
      - uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      - run: cd android && ./gradlew assembleRelease
      - uses: mobile-dev-inc/action-maestro-cloud@v1.1.1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: android/app/build/outputs/apk/release/app-release.apk
