name: Test Android Unit

on:
  workflow_call:
  workflow_dispatch:

jobs:
  java_unit_tests:
    name: 'Android / Unit'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Install npm dependencies
        working-directory: ./examples/Rn072
        run: yarn install --frozen-lockfile

      - name: Run unit tests
        working-directory: ./examples/Rn072/android
        run: ./gradlew testDebugUnitTest
