name: E2E tests (ios)

on:
  workflow_call:
  workflow_dispatch:

env:
  APP_PATH: ./examples/Rn071/ios/DerivedData/Build/Products/Release-iphonesimulator/Rn071.app
  PROJECT_NAME: Rn071
  EXAMPLE_SRC: ./examples/Rn071/src/**

jobs:
  test-ios-e2e:
    name: e2e tests
    runs-on: macos-13
    environment: e2e

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ${{ env.APP_PATH }}
            ${{ env.APP_PATH }}.dSYM
          key: ${{ runner.os }}-${{ hashFiles('src/**', 'ios/**', env.EXAMPLE_SRC ) }}

      - uses: mobile-dev-inc/action-maestro-cloud@v1.8.0
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: ${{ env.APP_PATH }}
          mapping-file: ${{ env.APP_PATH }}.dSYM
          include-tags: ios

      - name: Upload logs when workflow failed
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: BuildLogs
          path: |
            xcodebuild.log
            DerivedData/Logs/Test/*.xcresult
